In [2]:
import pandas as pd

df = pd.read_csv("../data/loan_approval_dataset.csv")

df.columns = df.columns.str.strip()

In [3]:
df = df.drop(columns=['loan_id'])

# Negative Values

In [4]:
asset_columns = [
    'residential_assets_value',
    'commercial_assets_value',
    'luxury_assets_value',
    'bank_asset_value'
]

for col in asset_columns:
    print(col)
    print((df[col] < 0).sum())

residential_assets_value
28
commercial_assets_value
0
luxury_assets_value
0
bank_asset_value
0

In [5]:
for col in asset_columns:

    negative_count = (df[col] < 0).sum()

    if negative_count > 0:

        median_val = df.loc[
            df[col] >= 0,
            col
        ].median()

        df[col] = df[col].apply(
            lambda x: median_val if x < 0 else x
        )

        print(f"{col}: {negative_count} negatives replaced")

residential_assets_value: 28 negatives replaced

In [6]:
for col in asset_columns:
    print(col, (df[col] < 0).sum())

residential_assets_value 0
commercial_assets_value 0
luxury_assets_value 0
bank_asset_value 0

# encoding

In [7]:
print(df['education'].value_counts())

print(df['self_employed'].value_counts())

print(df['loan_status'].value_counts())

education
Graduate        2144
Not Graduate    2125
Name: count, dtype: int64
self_employed
Yes    2150
No     2119
Name: count, dtype: int64
loan_status
Approved    2656
Rejected    1613
Name: count, dtype: int64

In [8]:
df['education'] = (
    df['education']
    .str.strip()
    .map({
        'Graduate': 1,
        'Not Graduate': 0
    })
)

df['self_employed'] = (
    df['self_employed']
    .str.strip()
    .map({
        'Yes': 1,
        'No': 0
    })
)

df['loan_status'] = (
    df['loan_status']
    .str.strip()
    .map({
        'Approved': 1,
        'Rejected': 0
    })
)

# Feature Engineering

In [9]:
df['total_assets'] = (
    df['residential_assets_value']
    + df['commercial_assets_value']
    + df['luxury_assets_value']
    + df['bank_asset_value']
)

In [10]:
df['loan_to_income_ratio'] = (
    df['loan_amount']
    / (df['income_annum'] + 1)
)

In [11]:
df['annual_payment'] = (
    df['loan_amount']
    / df['loan_term']
)

In [12]:
df['debt_service_ratio'] = (
    df['annual_payment']
    / (df['income_annum'] + 1)
)

In [13]:
df['assets_to_loan_ratio'] = (
    df['total_assets']
    / (df['loan_amount'] + 1)
)

In [14]:
df['income_per_dependent'] = (
    df['income_annum']
    / (df['no_of_dependents'] + 1)
)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   no_of_dependents          4269 non-null   int64
 1   education                 4269 non-null   int64
 2   self_employed             4269 non-null   int64
 3   income_annum              4269 non-null   int64
 4   loan_amount               4269 non-null   int64
 5   loan_term                 4269 non-null   int64
 6   cibil_score               4269 non-null   int64
 7   residential_assets_value  4269 non-null   float64
 8   commercial_assets_value   4269 non-null   int64
 9   luxury_assets_value       4269 non-null   int64
 10  bank_asset_value          4269 non-null   int64
 11  loan_status               4269 non-null   int64
 12  total_assets              4269 non-null   float64
 13  loan_to_income_ratio      4269 non-null   float64
 14  annual_payment            4269 non-null   float64
 15  debt_service_ratio        4269 non-null   float64
 16  assets_to_loan_ratio      4269 non-null   float64
 17  income_per_dependent      4269 non-null   float64
dtypes: float64(7), int64(11)
memory usage: 600.5 KB

In [16]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,total_assets,loan_to_income_ratio,annual_payment,debt_service_ratio,assets_to_loan_ratio,income_per_dependent
0,2,1,0,9600000,29900000,12,778,2400000.0,17600000,22700000,8000000,1,50700000.0,3.114583,2.491667e+06,0.259549,1.695652,3.200000e+06
1,0,0,1,4100000,12200000,8,417,2700000.0,2200000,8800000,3300000,0,17000000.0,2.975609,1.525000e+06,0.371951,1.393443,4.100000e+06
2,3,1,0,9100000,29700000,20,506,7100000.0,4500000,33300000,12800000,0,57700000.0,3.263736,1.485000e+06,0.163187,1.942761,2.275000e+06
3,3,1,0,8200000,30700000,8,467,18200000.0,3300000,23300000,7900000,0,52700000.0,3.743902,3.837500e+06,0.467988,1.716612,2.050000e+06
4,5,0,1,9800000,24200000,20,382,12400000.0,8200000,29400000,5000000,0,55000000.0,2.469388,1.210000e+06,0.123469,2.272727,1.633333e+06

In [17]:
df.describe()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,total_assets,loan_to_income_ratio,annual_payment,debt_service_ratio,assets_to_loan_ratio,income_per_dependent
count,4269.000000,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4.269000e+03,4.269000e+03,4269.000000,4.269000e+03,4269.000000,4.269000e+03,4269.000000,4269.000000,4.269000e+03
mean,2.498712,0.502225,0.503631,5.059124e+06,1.513345e+07,10.900445,599.936051,7.510658e+06,4.973155e+06,1.512631e+07,4.976692e+06,0.622160,3.258681e+07,2.984805,2.194899e+06,0.435513,2.253127,2.055050e+06
std,1.695910,0.500054,0.500045,2.806840e+06,9.043363e+06,5.709187,172.430401,6.476129e+06,4.388966e+06,9.103754e+06,3.250185e+06,0.484904,1.947621e+07,0.595495,2.597537e+06,0.398879,0.763243,2.003233e+06
min,0.000000,0.000000,0.000000,2.000000e+05,3.000000e+05,2.000000,300.000000,0.000000e+00,0.000000e+00,3.000000e+05,0.000000e+00,0.000000,5.000000e+05,1.499993,1.500000e+04,0.075000,0.749999,3.333333e+04
25%,1.000000,0.000000,0.000000,2.700000e+06,7.700000e+06,6.000000,453.000000,2.200000e+06,1.300000e+06,7.500000e+06,2.300000e+06,0.000000,1.630000e+07,2.464285,7.000000e+05,0.187500,1.774193,7.750000e+05
50%,3.000000,1.000000,1.000000,5.100000e+06,1.450000e+07,10.000000,600.000000,5.700000e+06,3.700000e+06,1.460000e+07,4.600000e+06,1.000000,3.150000e+07,2.999993,1.357143e+06,0.275176,2.145695,1.450000e+06
75%,4.000000,1.000000,1.000000,7.500000e+06,2.150000e+07,16.000000,748.000000,1.130000e+07,7.600000e+06,2.170000e+07,7.100000e+06,1.000000,4.720000e+07,3.499994,2.516667e+06,0.505747,2.628378,2.500000e+06
max,5.000000,1.000000,1.000000,9.900000e+06,3.950000e+07,20.000000,900.000000,2.910000e+07,1.940000e+07,3.920000e+07,1.470000e+07,1.000000,9.070000e+07,3.999999,1.935000e+07,2.000000,21.333262,9.900000e+06

In [20]:
df.to_csv(
    "../data/processed/loan_cleaned.csv",
    index=False
)